- name: "Create /etc/alertmanager"
  file:
    path: "/etc/alertmanager"
    state: "directory"
    mode: "0660"
    owner: "{{ alertmanager.user }}"
    group: "{{ alertmanager.group }}"

- name: "Install alertmanager.yaml"
  become: "true"
  template:
    src: "alertmanager.yaml.j2"
    dest: "/etc/alertmanager/alertmanager.yaml"
    mode: "0660"
    owner: "{{ alertmanager.user }}"
    group: "{{ alertmanager.group }}"

- name: "Start alertmanager.service"
  become: "true"
  systemd:
    name: "alertmanager"
    enabled: "yes"
    daemon_reload: "yes"
    state: "restarted"
